name: CDK Deploy

# Controls when the action will run. 
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.3

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5

      - name: Setup Python
        uses: actions/setup-python@v2.2.1

      - name: Build
        run: |
          # install npm packages and build Vue app
          cd web && \
          npm install . &&\
          npm run build

      - name: Test
        run: |
          go test ./...

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Deploy Dependencies
        run: |
          npm install aws-cdk
          pip install -r requirements.txt


      - name: Deploy
        run: |
          node_modules/.bin/cdk deploy \
          --require-approval never \
          --progress events \
          --no-color
        env:
          # App specific variables below
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          API_PORT: ${{ secrets.API_PORT }}
          # this is the reddit app id and secret
          APP_ID: ${{ secrets.REDDIT_APP_ID }}
          APP_SECRET: ${{ secrets.REDDIT_APP_SECRET }}
